"""Generate a YARA rule from a triage report (confirmed families and extracted indicators only)."""

from __future__ import annotations

import re
from datetime import datetime, timezone
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .engine import TriageReport

REFERENCE = "https://github.com/redhat1032/ransomware-triage"


def generate_yara_rule(report: TriageReport) -> str | None:
    """Return YARA source, or None when there is nothing specific enough to build a rule from.

    A rule is only emitted when it has at least one string, so the output always compiles.
    """
    strings: list[tuple[str, str, str]] = []  # (prefix, value, modifiers)
    seen: set[str] = set()

    def add(prefix: str, value: str, modifiers: str) -> None:
        key = value.lower()
        if len(value) >= 5 and key not in seen:
            seen.add(key)
            strings.append((prefix, value, modifiers))

    confirmed = report.confirmed_matches
    for match in confirmed[:2]:
        for ev in match.evidence:
            if ev.kind in {"note-keyword", "family-name"}:
                add("note", ev.value, "nocase ascii wide")
    for onion in report.iocs.onion_urls[:5]:
        add("onion", onion.split("/")[0].split(":")[0], "nocase ascii wide")
    for btc in report.iocs.bitcoin_addresses[:5]:
        add("btc", btc, "ascii wide")
    for email in report.iocs.emails[:5]:
        add("email", email, "nocase ascii wide")
    for tox in report.iocs.tox_ids[:3]:
        add("tox", tox, "nocase ascii wide")

    if not strings:
        return None

    family = confirmed[0].family if confirmed else "Unattributed"
    rule_name = "RansomTriage_" + _clean_rule_name(family)
    lines = [
        "/*",
        " * Generated by ransomtriage. Review before deploying; this is a starting point, not a vetted signature.",
        f" * Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}",
        " */",
        "",
        f"rule {rule_name}",
        "{",
        "    meta:",
        f'        description = "{_escape("Ransom note indicators for " + family)}"',
        f'        family = "{_escape(family)}"',
        '        author = "ransomtriage"',
        f'        reference = "{REFERENCE}"',
        f'        date = "{datetime.now(timezone.utc).strftime("%Y-%m-%d")}"',
        "    strings:",
    ]
    for index, (prefix, value, modifiers) in enumerate(strings, 1):
        lines.append(f'        ${prefix}_{index} = "{_escape(value)}" {modifiers}')
    lines += ["    condition:", "        any of them", "}", ""]
    return "\n".join(lines)


def _clean_rule_name(family: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_]", "_", family)
    cleaned = re.sub(r"_+", "_", cleaned).strip("_")
    return cleaned or "Generic"


def _escape(value: str) -> str:
    out = []
    for char in value:
        if char == "\\":
            out.append("\\\\")
        elif char == '"':
            out.append('\\"')
        elif 32 <= ord(char) < 127:
            out.append(char)
        else:
            out.append(f"\\x{ord(char) & 0xFF:02x}" if ord(char) < 256 else "?")
    return "".join(out)
